AWSTemplateFormatVersion: "2010-09-09"
Description: Sample IAM Role
Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - events.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - "iam:PassRole"
                  - "iam:GetRole"
                  - "iam:CreateRole"
                  - "iam:PutRolePolicy"
                  - "iam:DeleteRolePolicy"
                  - "iam:DeleteRole"
                  - "iam:AttachRolePolicy"
                  - "events:*"
                  - "cloudformation:*"
                  - "lambda:*"
                  - "apigateway:*"
                  - "s3:*"
                  - "logs:*"
                  - "dynamodb:*"
                  - "sqs:*"
                  - "application-autoscaling:*"
                Effect: Allow
                Resource: "*"
            Version: 2012-10-17
          PolicyName: example-policy
      RoleName: example-role
      Tags:
        - Key: 'Environment'
          Value: 'Test'
