# This is AWS Cloudformation Template
AWSTemplateFormatVersion: '2010-09-09'

Description: Pull Request Job

Parameters:
  ProjectName:
    AllowedPattern: '^[a-zA-Z0-9-_]*$'
    Description: >-
      Name to give the CodeBuild Project. For this sample, use the same name as
      your repository.
    MaxLength: '255'
    MinLength: '2'
    Type: String
  RepositoryUrl:
    Description: >-
      HTTPS Clone URL of the repository in GitHub. Example:
      'https://github.com/owner/repo.git'
    Type: String
  BuildSpecPath: # eg. codebuild/pull-request.yml
    Description: CodeBuild BuildSpec Path in Repo
    Type: String
  Repository:
    Description: GitHub Repository Name
    Type: String
  ServiceRole: # foo-codebuild-role
    Description: Service role name

Resources:
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref ProjectName
      Description: Pull Request Job
      ServiceRole: !Join
        - ''
        - - 'arn:aws:iam::'
          - !Ref 'AWS::AccountId'
          - ':role/'
          - !Ref ServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Auth:
          Type: OAUTH
        Location: !Ref RepositoryUrl
        Type: GITHUB
        BuildSpec: !Ref BuildSpecPath
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
      TimeoutInMinutes: '30'
      # Tags:
      #   - Key: 'Foo'
      #     Value: !Ref Foo
      #   - Key: 'Bar'
      #     Value: !Ref Bar
